---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-frontend-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/frontend-frontend-gitops
